export const ACTION_LOAD_BRAND_REQUEST = "ACTION_LOAD_BRAND_REQUEST";
export const ACTION_LOAD_BRAND_SUCCESS = "ACTION_LOAD_BRAND_SUCCESS";
export const ACTION_CREATE_BRAND_SUCCESS = "ACTION_CREATE_BRAND_SUCCESS";
