export const ACTION_LOAD_CATE_REQUEST = "ACTION_LOAD_CATE_REQUEST";
export const ACTION_LOAD_CATE_SUCCESS = "ACTION_LOAD_CATE_SUCCESS";
export const ACTION_CREATE_CATE_SUCCESS = "ACTION_CREATE_CATE_SUCCESS";
export const ACTION_REMOVE_CATE = "ACTION_REMOVE_CATE";