export const ACTION_LOAD_PRODUCT_REQUEST = "ACTION_LOAD_PRODUCT_REQUEST";
export const ACTION_LOAD_PRODUCT_SUCCESS = "ACTION_LOAD_PRODUCT_SUCCESS";
export const ACTION_REMOVE_PRODUCT = "ACTION_REMOVE_PRODUCT";
export const ACTION_LOAD_PRODUCT_DETAIL_SUCCESS = "ACTION_REMOVE_PRODUCT_DETAIL_SUCCESS";
export const ACTION_LOAD_PRODUCT_DETAIL_REQUEST = "ACTION_REMOVE_PRODUCT_DETAIL_REQUEST";