export const ACTION_LOAD_PRODUCT_REQUEST = "ACTION_LOAD_PRODUCT_REQUEST";
export const ACTION_LOAD_PRODUCT_SUCCESS = "ACTION_LOAD_PRODUCT_SUCCESS";
export const ACTION_REMOVE_PRODUCT = "ACTION_REMOVE_PRODUCT";